version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nzima-admin-ai-backend
    env_file:
      - backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    restart: unless-stopped
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: nzima-admin-ai-web
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped