version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nzima-admin-ai-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    restart: unless-stopped